SELECT * FROM MEMBER;

-- 로그인
SELECT MEMBER_NO, MEMBER_ID, MEMBER_NM, MEMBER_NNO, MEMBER_GENDER, TIER_LEVEL, ADMIN_FL, EMAIL
		TO_CHAR(ENROLL_DT, 'YYYY"년" MM"월" DD"일" HH24:MI:SS') ENROLL_DT
FROM "MEMBER"
WHERE MEMBER_ID = 'memberId'
AND MEMBER_PW = 'memberPw'
AND SECESSION_FL = 'N'

-- 회원 가입

-- 아이디 중복 체크
SELECT COUNT(*)
FROM "MEMBER"
WHERE MEMBER_ID = ?
AND SECESSION_FL = 'N';

-- 아이디 찾기
SELECT MEMBER_ID 
FROM "MEMBER"
WHERE MEMBER_NM = 'memberName'
AND MEMBER_NNO = 'memberNno'
AND SECESSION_FL = 'N'
-- 이메일 추가

-- 비밀번호 인증
SELECT COUNT(*)
FROM "MEMBER"
WHERE MEMBER_NO = ?
AND MEMBER_PW = ?
AND SECESSION_FL = 'N'

-- 비밀번호 변경
UPDATE "MEMBER" SET
MEMBER_PW = 'newMemberPw'
WHERE MEMBER_NO = 'memberNo'
AND SECESSION_FL = 'N'

-- 회원 탈퇴
UPDATE "MEMBER" SET
SECESSION_FL = 'Y'
WHERE MEMBER_NO = 'memberNo'
AND SECESSION_FL = 'N'

SELECT * FROM "MEMBER";

COMMIT;