-- 회원 테이블
DROP TABLE "MEMBER";

CREATE TABLE "MEMBER"(
	MEMBER_NO NUMBER CONSTRAINT MEMBER_NO_PK PRIMARY KEY,
	MEMBER_ID VARCHAR2(30) CONSTRAINT MEMBER_ID_NN NOT NULL,
	MEMBER_PW VARCHAR2(30) CONSTRAINT MEMBER_PW_NN NOT NULL,
	MEMBER_NM VARCHAR2(15) CONSTRAINT MEMBER_NM_NN NOT NULL,
	MEMBER_NNO CHAR(14) CONSTRAINT MEMBER_NNO_NN NOT NULL CONSTRAINT MEMBER_NNO_UK UNIQUE,
	MEMBER_GENDER CHAR(1) CONSTRAINT MEMBER_GENDER_CK CHECK(MEMBER_GENDER IN ('M','F')) CONSTRAINT MEMBER_GENDER_NN NOT NULL,
	ENROLL_DT DATE DEFAULT SYSDATE CONSTRAINT ENROLL_DT_NN NOT NULL,
	TIER_LEVEL CHAR(2) DEFAULT 'B4' CONSTRAINT TIER_LEVEL_NN NOT NULL,
	ADMIN_FL CHAR(1) DEFAULT 'N' CONSTRAINT ADMIN_FL_CK CHECK (ADMIN_FL IN ('Y','N')) CONSTRAINT ADMIN_FL_NN NOT NULL,
	SECESSION_FL CHAR(1) DEFAULT 'N' CONSTRAINT SECESSION_FL_CK CHECK(SECESSION_FL IN ('Y','N')) CONSTRAINT SECESSION_FL_NN NOT NULL,
	CONSTRAINT MEMBER_TIER_LEVEL FOREIGN KEY (TIER_LEVEL) REFERENCES TIER (TIER_LEVEL)
);


UPDATE "MEMBER" SET
EMAIL = 'kyh@gmail.com'
WHERE MEMBER_NO = 3;

COMMENT ON COLUMN "MEMBER".MEMBER_NO IS '회원 번호';
COMMENT ON COLUMN "MEMBER".MEMBER_ID IS '회원 아이디';
COMMENT ON COLUMN "MEMBER".MEMBER_PW IS '회원 비밀번호';
COMMENT ON COLUMN "MEMBER".MEMBER_NM IS '회원 이름';
COMMENT ON COLUMN "MEMBER".MEMBER_NNO IS '회원 주민등록번호';
COMMENT ON COLUMN "MEMBER".MEMBER_GENDER IS '회원 성별';
COMMENT ON COLUMN "MEMBER".ENROLL_DT IS '회원 가입일';
COMMENT ON COLUMN "MEMBER".TIER_LEVEL IS '티어 레벨';
COMMENT ON COLUMN "MEMBER".ADMIN_FL IS '관리자 여부';
COMMENT ON COLUMN "MEMBER".SECESSION_FL IS '탈퇴 여부';
COMMENT ON COLUMN "MEMBER".EMAIL IS '이메일';
ALTER TABLE MEMBER RENAME SYS_C008518 TO MEMBER_NO_PK;

ALTER TABLE ADD CONSTRAINT 

-- 회원 번호 PK 시퀀스
CREATE SEQUENCE SEQ_MEMBER_PK NOCACHE;

-- 샘플 데이터
INSERT INTO "MEMBER" (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NM, MEMBER_NNO ,MEMBER_GENDER)
	VALUES (SEQ_MEMBER_PK.NEXTVAL, 'user01', 'pass01', '스파이더맨', '931225-1324164', 'M');

INSERT INTO "MEMBER" (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NM, MEMBER_NNO ,MEMBER_GENDER, ADMIN_FL)
	VALUES (SEQ_MEMBER_PK.NEXTVAL, 'user02', 'pass02', '아이언맨', '870623-1189203', 'M', 'Y');

COMMIT;

SELECT * FROM "MEMBER"

UPDATE "MEMBER" SET
SECESSION_FL = 'N'
WHERE MEMBER_NO = 1;

DELETE FROM ""




-- 티어 레벨 테이블
DROP TABLE TIER;
CREATE TABLE TIER (
	TIRE_LEVEL CHAR(2) CONSTRAINT TIER_LEVEL_PK PRIMARY KEY,
	MIN_COUNT NUMBER CONSTRAINT MIN_COUNT_NN NOT NULL,
	MAX_COUNT NUMBER CONSTRAINT MAX_COUNT_NN NOT NULL,
	TIER_NM VARCHAR2(20) CONSTRAINT TIER_NM_NN NOT NULL
);

COMMENT ON COLUMN TIER.TIER_LEVEL IS '티어 레벨';
COMMENT ON COLUMN TIER.MIN_COUNT  IS '최소 갯수';
COMMENT ON COLUMN TIER.MAX_COUNT  IS '최대 갯수';
COMMENT ON COLUMN TIER.TIER_NM IS '티어 이름';

-- 티어 레벨 샘플 데이터
INSERT INTO TIER VALUES ('B4', 0, 4, '브론즈4');
INSERT INTO TIER VALUES ('B3', 5, 9, '브론즈3');
INSERT INTO TIER VALUES ('B2', 10, 14, '브론즈2');
INSERT INTO TIER VALUES ('B1', 15, 19, '브론즈1');
INSERT INTO TIER VALUES ('S4', 20, 24, '실버4');
INSERT INTO TIER VALUES ('S3', 25, 29, '실버3');
INSERT INTO TIER VALUES ('S2', 30, 34, '실버2');
INSERT INTO TIER VALUES ('S1', 35, 39, '실버1');
COMMIT;

SELECT * FROM TIER;

SELECT * FROM "MEMBER";
SELECT '1' FROM DUAL;

-- 회원별 단어 기록 테이블
CREATE TABLE WORD_RECODE (
	RECODE_NO NUMBER CONSTRAINT RECODE_NO_PK PRIMARY KEY,
	ACCURATE_COUNT NUMBER DEFAULT 0 CONSTRAINT ACCURATE_COUNT_NN NOT NULL,
	WRONG_COUNT NUMBER DEFAULT 0 CONSTRAINT WRONG_COUNT_NN NOT NULL,
	MEMBER_NO NUMBER CONSTRAINT WORD_RECODE_MEMBER REFERENCES "MEMBER" (MEMBER_NO) CONSTRAINT WORD_RECODE_MEMBER_NN NOT NULL,
	WORD_NO NUMBER CONSTRAINT WORD_RECODE_WORD REFERENCES "WORD" (WORD_NO) CONSTRAINT WORD_RECODE_WORD_NN NOT NULL
);
COMMENT ON COLUMN  WORD_RECODE.RECODE_NO IS '기록 번호';
COMMENT ON COLUMN  WORD_RECODE.ACCURATE_COUNT IS '정답 횟수';
COMMENT ON COLUMN  WORD_RECODE.WRONG_COUNT IS '오답 횟수';
COMMENT ON COLUMN  WORD_RECODE.MEMBER_NO IS '회원 번호';
COMMENT ON COLUMN  WORD_RECODE.WORD_NO IS '단어 번호';

-- WORD_RECODE 시퀀스 생성
CREATE SEQUENCE SEQ_WORD_RECODE_PK NOCACHE;







