-- 시험 기록 테이블
DROP TABLE TEST_RECODE;
CREATE TABLE TEST_RECODE (
	TEST_NO NUMBER CONSTRAINT TEST_RECODE_PK PRIMARY KEY,
	TEST_SCORE NUMBER DEFAULT 0 CONSTRAINT TEST_SCORE_NN NOT NULL,
	TEST_DT DATE DEFAULT SYSDATE CONSTRAINT TEST_DT_NN NOT NULL,
	MEMBER_NO NUMBER CONSTRAINT TEST_RECODE_MEMBER REFERENCES "MEMBER"(MEMBER_NO) CONSTRAINT TEST_RECODE_MEMBER_NN NOT NULL
);
COMMENT ON COLUMN TEST_RECODE.TEST_NO IS '시험 번호';
COMMENT ON COLUMN TEST_RECODE.TEST_SCORE IS '시험 점수';
COMMENT ON COLUMN TEST_RECODE.TEST_DT IS '시험 날짜';
COMMENT ON COLUMN TEST_RECODE.MEMBER_NO IS '회원 번호';

-- 시험 기록 테이블 PK 시퀀스 생성
CREATE SEQUENCE SEQ_TEST_RECODE_PK NOCACHE;

-- 문제 테이블
DROP TABLE QUESTION;
CREATE TABLE QUESTION (
	EXAMPLE VARCHAR2(200) CONSTRAINT EXAMPLE_NN NOT NULL,
	CORRECT_ANSWER NUMBER CONSTRAINT CORRECT_ANSWER_CK CHECK(CORRECT_ANSWER BETWEEN 1 AND 5) CONSTRAINT CORRECT_ANSWER_NN NOT NULL,
	USER_ANSWER NUMBER CONSTRAINT USER_ANSWER_CK CHECK(USER_ANSWER BETWEEN 1 AND 5) CONSTRAINT USER_ANSWER_NN NOT NULL,
	WORD_NO NUMBER CONSTRAINT QUESTION_WORD REFERENCES WORD (WORD_NO) CONSTRAINT QUESTION_WORD_NN NOT NULL,
	TEST_NO NUMBER CONSTRAINT QUESTION_TEST_RECODE REFERENCES TEST_RECODE (TEST_NO) CONSTRAINT QUESTION_TEST_RECODE_NN NOT NULL
);


SELECT * FROM QUESTION;

SELECT SEQ_TEST_RECODE_PK.NEXTVAL FROM DUAL;
COMMENT ON COLUMN QUESTION.QUESTION_NO IS '문제 번호';
COMMENT ON COLUMN QUESTION.EXAMPLE IS '보기 1 ~ 5번';
COMMENT ON COLUMN QUESTION.CORRECT_ANSWER IS '정답 번호';
COMMENT ON COLUMN QUESTION.USER_ANSWER IS '사용자 답변 번호';
COMMENT ON COLUMN QUESTION.WORD_NO IS '단어 번호';
COMMENT ON COLUMN QUESTION.TEST_NO IS '시험 번호';

DROP TABLE WORD_RECODE;
ROLLBACK;



COMMIT;
COMMIT;
-- 문제 테이블 PK 시퀀스 생성
CREATE SEQUENCE SEQ_QUESTION_PK NOCACHE;

-- 단어 기록 테이블 PK 시퀀스 생성
CREATE SEQUENCE SEQ_WORD_RECODE_PK NOCACHE;

CREATE TABLE WORD_RECODE (
	ACCURAT_COUNT NUMBER DEFAULT 0 CONSTRAINT "ACCURATE_COUNT_NN" NOT NULL,
	"WRONG_COUNT" NUMBER DEFAULT 0 CONSTRAINT "WRONG_COUNT_NN" NOT NULL,
	"MEMBER_NO" NUMBER CONSTRAINT WORD_RECODE_MEMBER REFERENCES MEMBER CONSTRAINT "WORD_RECODE_MEMBER_NN" NOT NULL,
	"WORD_NO" NUMBER CONSTRAINT WORD_RECODE_WORD REFERENCES WORD CONSTRAINT "WORD_RECODE_WORD_NN" NOT NULL
);


INSERT INTO (RECODE_NO, MEMBER_NO, WORD_NO)
VALUES(SEQ_WORD_RECODE_PK.NEXTVAL, ?, ?)