-- 랜덤한 단어 10개 (똣도 랜덤 1개)
-- 단어 번호, 단어 이름, 뜻 이름 조회
SELECT * FROM
	(SELECT WORD_NO, WORD_NM, 
		(SELECT MEANING_NM FROM 
			(SELECT MEANING_NM
			FROM MEANING
			WHERE MEANING.WORD_NO = WORD.WORD_NO
			AND DELETE_FL = 'N'
			ORDER BY DBMS_RANDOM.VALUE)
		WHERE ROWNUM < 2) MEANING_NM
	FROM WORD 
	WHERE DELETE_FL = 'N'
	ORDER BY DBMS_RANDOM.VALUE)
WHERE ROWNUM < 11

-- 랜덤한 뜻 40개 가져오기
SELECT * 
FROM (SELECT MEANING_NM 
	FROM MEANING
	WHERE WORD_NO NOT IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
	ORDER BY DBMS_RANDOM.VALUE)
WHERE ROWNUM<41;

-- 단어 기록 이미 등록 여부 확인
WITH CHECK_WORD AS (
	SELECT WORD_NO
	FROM WORD 
	WHERE WORD_NO IN (1, 21, 23, 24, 31))
SELECT WORD_NO, NVL(RECODE_NO, 0)
FROM WORD_RECODE
FULL JOIN CHECK_WORD USING(WORD_NO)
WHERE MEMBER_NO = 1;


WITH CHECK_WORD AS (
	SELECT WORD_NO
	FROM WORD 
	WHERE WORD_NO IN (1, 21, 23, 24, 31))
SELECT * 
FROM WORD_RECODE
RIGHT JOIN CHECK_WORD USING(WORD_NO)
WHERE MEMBER_NO = 1;




-- 다음 시험 번호 가져오기
SELECT SEQ_TEST_RECODE_PK.NEXTVAL FROM DUAL;

SELECT * FROM TEST_RECODE;

INSERT INTO TEST_RECODE (TEST_NO, TEST_SCORE, MEMBER_NO)
VALUES(1, 30, 2);


-- 문제 등록
INSERT INTO QUSETION (WORD_NO, TEST_NO, EXAMPLE, CORRECT_ANSWER, USER_ANSWER)
VALUES(?, ?, ?, ?, ?)

-- 첫 기록 검사
SELECT COUNT(*) FROM WORD_RECODE WHERE MEMBER_NO = 1;

-- 단어 기록 카운트 증가
SELECT * FROM WORD_RECODE;

UPDATE WORD_RECODE SET
ACCURATE_COUNT = ACCURATE_COUNT + 1
WHERE WORD_NO ?
AND MEMBER_NO ?

DELETE FROM TEST_RECODE;
DELETE FROM QUESTION;
DELETE FROM WORD_RECODE;

SELECT * FROM TEST_RECODE;
SELECT * FROM QUESTION;
SELECT * FROM WORD_RECODE;
COMMIT;

SELECT COUNT(*) "CHECK"
		FROM WORD_RECODE
		WHERE WORD_NO = 15
		AND MEMBER_NO = 1;

-- 시험 목록 조회
