-- 모든 단어 조회
SELECT WORD_NO, WORD_NM, MEANING.POS_CODE, MEANING_NO, MEANING_NM,
	(SELECT POS_NM FROM PART_OF_SPEECH P WHERE P.POS_CODE = MEANING.POS_CODE) POS_NM
FROM WORD
JOIN MEANING USING(WORD_NO)
WHERE WORD.DELETE_FL = 'N'
AND MEANING.DELETE_FL = 'N'

-- 단어 하나 조회
SELECT WORD_NO, WORD_NM, MEANING.POS_CODE, MEANING_NO, MEANING_NM,
	(SELECT POS_NM FROM PART_OF_SPEECH P WHERE P.POS_CODE = MEANING.POS_CODE) POS_NM
FROM WORD
JOIN MEANING USING(WORD_NO)
WHERE WORD.DELETE_FL = 'N'
AND MEANING.DELETE_FL = 'N'
AND WORD_NM = 'wordName';

-- 단어 검색
SELECT WORD_NO, WORD_NM, MEANING.POS_CODE, MEANING_NO, MEANING_NM,
	(SELECT POS_NM FROM PART_OF_SPEECH P WHERE P.POS_CODE = MEANING.POS_CODE) POS_NM
FROM WORD
JOIN MEANING USING(WORD_NO)
WHERE WORD.DELETE_FL = 'N'
AND MEANING.DELETE_FL = 'N'
-- AND WORD_NM LIKE '%'|| ? ||'%';
-- AND MEANING_NM LIKE '%'|| ? ||'%';
-- AND POS_CODE IN (SELECT POS_CODE FROM PART_OF_SPEECH WHERE POS_NM LIKE '%사%');
ORDER BY WORD_NO;

-- 다음 단어 번호 구하기
SELECT SEQ_WORD_PK.NEXTVAL FROM DUAL;

-- 단어 추가
INSERT INTO WORD VALUES (SEQ_WORD_PK.NEXTVAL, 'release', DEFAULT);


DELETE FROM MEANING
WHERE MEANING_NO = 32;
COMMIT;
SELECT * FROM MEANING
WHERE WORD_NO =1;


-- 문제 만들기

-- 10개 무작위 단어 무작위 뜻과 함께 가져오기
SELECT WORD_NO, WORD_NM
FROM (SELECT WORD_NO, WORD_NM, ()
	FROM WORD
	ORDER BY DBMS_RANDOM.VALUE)
WHERE ROWNUM <= 10;

-- 무작위 뜻 40개 가져오기
SELECT DISTINCT WORD_NO, WORD_NM, POS_CODE, MEANING_NO, MEANING_NM FROM 
(SELECT DISTINCT WORD_NO, WORD_NM, MEANING.POS_CODE, MEANING_NO, MEANING_NM,
	(SELECT POS_NM FROM PART_OF_SPEECH P WHERE P.POS_CODE = MEANING.POS_CODE) POS_NM
FROM WORD
JOIN MEANING USING(WORD_NO)
WHERE WORD.DELETE_FL = 'N'
AND MEANING.DELETE_FL = 'N'
ORDER BY DBMS_RANDOM.VALUE)
WHERE ROWNUM <= 40;


